Ops 992 notification api
HHS/OPRE-OPS pull request #1150
Opened 2023-06-27 16:58 UTC by johndeange

## What changed

Added initial Notification Center.

## Issue

https://app.zenhub.com/workspaces/opre-ops-62d197b4c468970013bcd2ec/issues/gh/hhs/opre-ops/992

## How to test

1. Log into the application and click the bell icon next to your email.
2. Add a Notification object to the DB
3. The notification should appear in the UI within 5 s

2023-06-27 18:23 UTC, fpigeonjr requested changes
tested locally and in `development` and looks good. 
Found some minor linting issues and suggestions for Modal and new Notification component.

2023-06-27 18:23 UTC, fpigeonjr commented on frontend/src/components/UI/Header/Header.jsx
> +import NotificationCenter from "../NotificationCenter/NotificationCenter";
linter error for being unused?

2023-06-27 18:23 UTC, fpigeonjr commented on frontend/src/components/UI/Header/Search.jsx
> +import NotificationCenter from "../NotificationCenter/NotificationCenter";
linter error

2023-06-27 18:23 UTC, fpigeonjr commented on frontend/src/components/UI/Notification/Notification.jsx
can we add an `index.js` in this file with the default export for Notifcation.jsx? This way we can import in other files like `import Notification from '../Notification` without the extra `Notification/Notification`?

2023-06-27 18:23 UTC, fpigeonjr commented on frontend/src/components/UI/Modal/Modal.jsx
> +                                {description && description instanceof Array && (
I am seeing this warning in terminal

Failed prop type: Invalid prop `description` of type `array` supplied to `Modal`, expected `string`.

2023-06-27 18:23 UTC, fpigeonjr commented on frontend/src/components/UI/Modal/Modal.jsx
> +                                {description && description instanceof Array && (
wonder if we need to check array length is more than one here?
`description.length > 0 && (
// render the thing
)`

2023-06-27 18:23 UTC, fpigeonjr commented on openapi.yml
> +  /api/v1/notifications/:
nice, glad we are keeping this up-to-date

2023-06-27 20:04 UTC, jonnalley commented
This is a great step forward

2023-06-27 20:58 UTC, fpigeonjr approved these changes
thanks @johndeange.

2023-06-28 15:22 UTC, stevtek approved these changes

2023-06-28 18:18 UTC, merged