Ops 1198 bell icon
HHS/OPRE-OPS pull request #1202
Opened 2023-07-12 19:42 UTC by johndeange

## What changed

Use different icon depending on if there are notifications.

## Issue

https://github.com/HHS/OPRE-OPS/issues/1198

## How to test

1. Log into the app and click the bell to see your notifications.
2. Clear the notifications.
3. The bell icon should change.

## Screenshots

![image](https://github.com/HHS/OPRE-OPS/assets/1972158/59869fde-19e2-4f9f-97c6-22c4ab8bda33)

![image](https://github.com/HHS/OPRE-OPS/assets/1972158/7675d367-7e88-49bb-a00d-83b58d584233)

2023-07-12 19:43 UTC, tdonaworth approved these changes

2023-07-12 21:25 UTC, fpigeonjr requested changes
minor css improvements

2023-07-12 21:25 UTC, fpigeonjr commented on frontend/src/components/Auth/AuthSection.jsx
> +                        <div style={{ paddingRight: "20px" }}>
pls use uswds spacing units `padding-right-205`

2023-07-12 21:25 UTC, fpigeonjr commented on frontend/src/components/Auth/AuthSection.jsx
> +                        <div style={{ paddingRight: "20px" }}>
pls use uswds spacing units `padding-right-205`

2023-07-13 13:43 UTC, fpigeonjr approved these changes
👍🏿

2023-07-13 14:08 UTC, merged