updates eslint based Vite
HHS/OPRE-OPS pull request #1234
Opened 2023-07-18 18:47 UTC by fpigeonjr

updates eslint based Vite
- fixes linter issues

## What changed

updates eslint based Vite

## Issue

#1111 

## How to test

run `yarn lint` 

## Links

_If relevant, e.g. for a link to a piece of markdown documentation_

2023-07-18 19:31 UTC, fpigeonjr commented on frontend/src/api/patchAgreements.js
@stevtek, may need some help resolving these linter errors here.

2023-07-18 20:40 UTC, stevtek approved these changes

2023-07-20 13:48 UTC, tdonaworth requested changes
version pinning

2023-07-20 13:48 UTC, tdonaworth commented on frontend/package.json
> +        "eslint-config-prettier": "^8.8.0",
don't we want to pin to a specific version?

2023-07-20 13:48 UTC, tdonaworth commented on frontend/package.json
> +        "eslint-plugin-react": "^7.32.2",
same, we should pin to the exact version on these.

2023-07-20 13:54 UTC, johndeange approved these changes

2023-07-20 19:34 UTC, tdonaworth approved these changes

2023-07-20 21:07 UTC, merged