Ops 970 hhs ams OIDC poc
HHS/OPRE-OPS pull request #1304
Opened 2023-08-08 02:21 UTC by tdonaworth

## What changed

* Wired up HHS Authentication Provider
* Created `MultiAuth` Login schema
* Created `FakeAuth` Login for offline / dev / demo login
* Created User Edit page, mostly for `new user` profile confirmation

## Issue

#970 

## How to test

TBD

## Screenshots

TBD

## Links

TBD

2023-08-08 19:27 UTC, xlorepdarkhelm requested changes
Looks pretty good overall, several pieces of commented code, one other note about PUT and PATCH for Users.

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/ops/resources/users.py
Do we still need commented code?

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/ops/resources/users.py
> +
And here

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/ops/resources/users_schemas.py
> +# from marshmallow import validates_schema
Commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/ops/utils/auth.py
> +    # current_app.logger.debug(f"********  provider_uris={provider_uris}")
Commented out code.

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/ops/utils/auth.py
> +    # }
More commented code.

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/ops/utils/authentication.py
> +            # current_app.logger.debug(f"get_user_info: user_jwt_response={user_jwt}")
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/ops/utils/user.py
> +                # last_name=userinfo["family_name"],
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/tests/ops/auth/test_oidc_controller.py
> +    # assert event.event_status == OpsEventStatus.FAILED
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on backend/ops_api/tests/ops/users/test_users.py
> +#     assert response.status_code == 400
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on frontend/src/components/Auth/AuthSection.jsx
> +// }
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on frontend/src/components/Auth/MultiAuthSection.jsx
> +// }
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on frontend/src/components/Auth/MultiAuthSection.jsx
> +        //console.debug("FakeUser Logged In!");
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on frontend/src/components/Auth/auth.js
>      //   state=abcdefghijklmnopabcdefghijklmnop
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on frontend/src/components/UI/Form/Input/Input.jsx
> +    // }
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on frontend/src/components/Users/UserInfoForm/EditUserForm.jsx
> +            // }).unwrap();
commented code

2023-08-08 19:27 UTC, xlorepdarkhelm commented on frontend/src/components/Users/UserInfoForm/EditUserForm.jsx
> +            // console.log(`Update Response Data: ${JSON.stringify(response)}`);
here too

2023-08-09 13:36 UTC, tdonaworth commented on backend/ops_api/ops/resources/users.py
> +# from desert import schema
intend on using schema validation, working through debug issues

2023-08-09 22:40 UTC, fpigeonjr commented
🥩 this is a beefy PR
<img width="227" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/312e7fb0-7115-48c0-8772-c4670e078ab9">

2023-08-22 21:04 UTC, johndeange commented on frontend/src/components/UI/NotificationCenter/NotificationCenter.jsx
> +    } = useGetNotificationsByUserIdQuery(userId, { pollingInterval: 500000 });
Do we want to revert this?

2023-08-22 21:41 UTC, stevtek approved these changes

2023-08-23 12:01 UTC, tdonaworth commented on .github/workflows/unit_test_reusable.yml
> +        run: yarn test:e2e --spec ./cypress/e2e/loginPage.cy.js
good catch 👍

2023-08-23 12:01 UTC, tdonaworth commented on frontend/src/components/UI/NotificationCenter/NotificationCenter.jsx
> +    } = useGetNotificationsByUserIdQuery(userId, { pollingInterval: 500000 });
👍

2023-08-23 12:03 UTC, tdonaworth commented
Can't be sure, but still getting an `SSL_ERROR_HANDSHAKE_FAILURE_ALERT` on the HHS AMS Login. I saw this prior, and hoped it was temporary. Will create a ticket to see if this is something on the HHS side, or simply because we're trying to connect from an `http` localhost site.

![image](https://github.com/HHS/OPRE-OPS/assets/56687505/e681db7f-89cb-44d1-a616-0c136e89b3ed)

2023-08-23 17:13 UTC, tdonaworth commented
> Can't be sure, but still getting an `SSL_ERROR_HANDSHAKE_FAILURE_ALERT` on the HHS AMS Login. I saw this prior, and hoped it was temporary. Will create a ticket to see if this is something on the HHS side, or simply because we're trying to connect from an `http` localhost site.
> 
> ![image](https://user-images.githubusercontent.com/56687505/262662180-e681db7f-89cb-44d1-a616-0c136e89b3ed.png)

Escalated to AMS Support: The AMS Helpdesk ticket number is 853834

2023-08-23 21:06 UTC, johndeange approved these changes

2023-08-23 21:19 UTC, merged