Cj/123/setup local server
HHS/OPRE-OPS pull request #143
Opened 2021-08-24 02:02 UTC by carjug

TBD

2021-08-24 19:38 UTC, alexsoble requested changes
👋 👋  I love seeing the README starting to get built out here!

When I follow the README instructions, the app builds locally and all seemed fine at first:

```
[2021-08-24 19:34:33 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-08-24 19:34:33 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
```

However, when I tried to visit `/hello_world/` or `/admin/` locally, I got a 500 Internal Server Error error in response. 

Stack trace: 

```
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/django/core/handlers/base.py", line 129, in get_response
    set_urlconf(settings.ROOT_URLCONF)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/django/conf/__init__.py", line 83, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'
```

Looks like a settings issue! @carjug and @amymok, do you see something different?

2021-08-24 19:42 UTC, alexsoble commented
Also @carjug on the "run docker in cloud.gov" topic, some relevant docs! https://cloud.gov/docs/deployment/docker/

My default would be to use the supported buildpack in production because the "pro"s there are big ones:

> It “just works”.
> Automatic and constant security updates.
> All you need to do is write code.

And on the mirror image side, the cons of running custom docker images in production on cloud.gov: 

> Added responsibility for all security updates and bug fixes.
> More compliance responsibility means more work.

2021-08-24 19:54 UTC, carjug commented
@alexsoble oh whoops! I moved the settings file into its own directory last minute, i wonder if that's the issue. Let me see what I can do 🕵️‍♀️ !

2021-08-24 21:54 UTC, amymok commented
@carjug I think there are couple things I am seeing that may cause this error:
- Move of the `settings.py` file: You will now need to specific the `--settings` to the right path because it is no longer the default choice.  Some resources:
  - https://docs.djangoproject.com/en/3.2/topics/settings/#designating-the-settings
  - https://stackoverflow.com/questions/49235486/how-to-properly-runserver-on-different-settings-for-django/49236676
- May want to revisit the file structures, I am unsure if this is a cause or not:
  - Probably need to create another `opre_ops` level to put in `settings.py` folder, wsgi.py, and some other files.  There may be some upper level `opre_ops` folder we can remove so it doesn't need to go as deep.  Some examples:
    - The [first answer](https://stackoverflow.com/questions/49235486/how-to-properly-runserver-on-different-settings-for-django/49236676) has an example.
    - [Settings](https://github.com/18F/tock) are in the 3rd level of `tock`
    - [Settings](https://github.com/18F/usda-fns-ingest) at 2nd level at `usda-fns-ingest`

2021-08-24 23:49 UTC, alexsoble commented
Building on what @amymok mentioned about the file/folder nesting: `settings.py` and `.env.py` need to be on the same level in the hierarchy because `settings.py` calls `.env.py`:

```
from .env import env
```

2021-08-24 23:50 UTC, alexsoble commented
@carjug I did some debugging on this and made progress, happy to pair with you on it tomorrow if you're blocked.

2021-08-25 04:57 UTC, carjug commented
Ok @alexsoble @amymok I just moved the settings file back to where it was originally, so not inside its own `settings` dir. Given that there is a separate ticket to address separating settings out per environment I vote to just leave as is and address the settings issue in that ticket. Is that good by y'all? Please pull down again and test locally if you'd like!!

2021-08-25 05:15 UTC, amymok requested changes
I am able to get to http://localhost:8080/hello_world, but I ran into an issue when navigating to http://localhost:8080/admin.  I got an `ImproperlyConfigured at /admin/: settings.DATABASES is improperly configured. Please supply the NAME value.`

I believe the admin interface is out of scope, so you may want to comment out the admin url for now.

Other than those, it looks good to me!

2021-08-25 05:15 UTC, amymok commented on README.md
> +```
Add instruction on how to run it:
Navigate to http://localhost:8080/helloworld in your browser

2021-08-25 05:16 UTC, amymok requested changes

2021-08-25 05:16 UTC, amymok commented on README.md
> +1. Make sure you have Docker installed locally
installed and *started* locally.  I ran into an issue because I didn't start Docker.

2021-08-25 15:26 UTC, alexsoble commented
@carjug 🎉, works for me locally with that settings file change!

2021-08-25 15:28 UTC, alexsoble commented
[suggestion] Remove the `start-web.sh` script as part of this PR, since it's deprecated now that we are using `Procfile`?

2021-08-25 15:53 UTC, carjug commented
@amymok I addressed your requested changes! lmk what you think :)

2021-08-25 15:57 UTC, carjug commented
> [question] Do we want to have some kind of manual-deploy-to-cloud-dot-gov-and-verify-that-everything-works step before final approval and merge?

@alexsoble given that this ticket is for running locally only, I would say "idk" just because nothing will have fundamentally changed in terms of how the app is currently running on dev/cloud.gov (still using the `start-web.sh` script) as that will be addressed in a later ticket (IIRC). We can talk more about this in co-working if you want!

2021-08-25 16:09 UTC, alexsoble commented
@carjug Ah, I didn't realize that the cloud.gov app is still using `start-web.sh`. I wonder if introducing a Procfile will change things on cloud.gov at all? Like will CloudFoundry see the Procfile and use it? https://docs.cloudfoundry.org/buildpacks/prod-server.html

Anyways, I digress ... keeping this scope to local development for now makes sense to me! Build out a good local dev experience first, other things can come later!

2021-08-25 16:20 UTC, amymok approved these changes
LGTM!

2021-08-25 16:20 UTC, merged