Cml/add alembic dev
HHS/OPRE-OPS pull request #2072
Opened 2024-03-14 17:38 UTC by devops-chris

## What changed

- Built for Alembic to run in data-tools for cloud
- Updated the deployment to support. 
- Moved to non-terraform deployments
- Cleaned up

2024-03-15 12:29 UTC, devops-chris commented on backend/alembic/env.py
@johndeange - I particularly wanted your eyes on this, just for awareness. Alembic was just defaulting to the local env with no access to the env variables used for deployments, so I added those here.

2024-03-15 12:34 UTC, tdonaworth approved these changes

2024-03-18 14:01 UTC, johndeange requested changes

2024-03-19 18:38 UTC, johndeange approved these changes

2024-03-19 18:38 UTC, merged