Ops 441 initial page and combobox
HHS/OPRE-OPS pull request #2653
Opened 2024-08-07 13:49 UTC by johndeange

## What changed

- Added `User Admin` page (only accessible by users with the `USER_ADMIN` role)
- Updated `UserInfo` component to make editable by `USER_ADMIN` (and display human readable values)
- Added new RTKQ API `opsAuthAPI`
- Improvements/fixes to `msw` JS stub (`mocks.js`)

## Issue

https://github.com/HHS/OPRE-OPS/issues/441

## How to test

1. Testing that only `USER_ADMIN` role can access the `User Admin` menu option

- Login as Admin and the menu option should not be visible.
- Login as Division Director and the option should be visible (since DD is a `USER_ADMIN`)

2. Testing that only `USER_ADMIN` has an editable view of `UserInfo`

- Login as Admin (or any user other than Division Director)
- Click on the user's email address in the upper right of the page to go to the `User Details` page.
- Verify that the `UserInfo` is read-only.

- Login as Division Director
- Click on the user's email address in the upper right of the page to go to the `User Details` page.
- Verify that the `UserInfo` is editable, i.e. has combo boxes for status, role, and division

N.B. The actual persistence of the `UserInfo` changes will be covered in a future PR.   (There is already too much going on in this PR)

## Screenshots

_If relevant, e.g. for a front-end feature_

## Definition of Done Checklist
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] Form validations updated

2024-08-07 22:22 UTC, fpigeonjr commented
👀
<img width="169" alt="image" src="https://github.com/user-attachments/assets/a6b891f1-ae0f-438c-ad6f-7a9946856f75">

2024-08-07 22:38 UTC, fpigeonjr commented
> Login as Division Director and the option should be visible (since DD is a USER_ADMIN)

When logged in as as Director Dave, I am not seeing the **User Admin** tab

<img width="842" alt="SCR-20240807-plho" src="https://github.com/user-attachments/assets/1f66a88c-82f0-4918-9ed3-208e2318e5f5">

2024-08-07 22:44 UTC, fpigeonjr commented
🥇 UserInfo is only editable by the Budget Team 

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/5ed7b473-377e-4de8-804b-8be99442728d">

2024-08-07 22:49 UTC, fpigeonjr commented on frontend/src/components/Users/UserInfo/UserInfo.jsx
> +        { id: 2, name: "INACTIVE" },
ACTIVE, INACTIVE, LOCKED would be a good use-case for an ENUM

2024-08-07 22:50 UTC, fpigeonjr commented on frontend/src/components/Users/UserInfo/UserInfo.jsx
> +    useEffect(() => {
🔥nice useEffect

2024-08-07 22:53 UTC, fpigeonjr commented on frontend/src/components/Users/UserInfo/UserInfo.module.css
> +    display: flex;
may be able to use USWDS classes here like: "display-flex, flex-align-center"?

2024-08-07 22:57 UTC, fpigeonjr requested changes
⭐ User-Admin is much improved. Have a few observations that don't pass the how-to-test section.

2024-08-08 13:10 UTC, johndeange commented
I apologize @fpigeonjr , I messed up the "How to Test" section.  You are correct that the test user with the `USER_ADMIN` role is the `Budget Team` user.  I updated the testing instructions.

2024-08-08 15:44 UTC, maiyerlee approved these changes
I followed the steps in How To Test and the changes checked out.

2024-08-08 16:08 UTC, fpigeonjr approved these changes

2024-08-08 16:09 UTC, fpigeonjr commented on frontend/src/components/Users/UserInfo/UserInfo.constants.js
> +export const USER_STATUS = {
🤩

2024-08-08 17:34 UTC, merged