feat:Created-CAN-funding-received-endpoint
HHS/OPRE-OPS pull request #2866
Opened 2024-09-30 18:56 UTC by Santi-3rd

## What changed

Created a new endpoint for CAN-Funding-Received.

## Issue

#2836 

## How to test

Run backend tests.

## Definition of Done Checklist
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] Form validations updated

2024-10-01 13:39 UTC, rajohnson90 requested changes

2024-10-01 13:39 UTC, rajohnson90 commented on backend/openapi.yml
> +        budget:
Either you need to change the budget in this to funding, or in your exampling you need to change funding to budget. Either way, just appears to be a minor issue with inconsistency of naming between your CreateUpdate object and the Example.

2024-10-01 21:04 UTC, rajohnson90 approved these changes

2024-10-01 21:22 UTC, fpigeonjr reviewed
🤩 looks good but will defer to others

2024-10-02 18:49 UTC, johndeange approved these changes
Great job! Please also see my comments.

2024-10-02 18:49 UTC, johndeange commented on backend/ops_api/ops/services/can_funding_received.py
> +            old_funding: CANFundingReceived = current_app.db_session.execute(
This can more concisely be expressed as: `old_funding = current_app.db_session.get(CANFundingReceived, id)`

2024-10-02 18:49 UTC, johndeange commented on backend/ops_api/ops/services/can_funding_received.py
> +        stmt = select(CANFundingReceived).where(CANFundingReceived.id == id).order_by(CANFundingReceived.id)
No need for `order_by` here - you're only returning 1 record.

2024-10-03 14:30 UTC, merged