Podman issues
HHS/OPRE-OPS pull request #3033
Opened 2024-11-06 18:14 UTC by johndeange

## What changed

Changes needed to get `podman` working on my M3 Mac (`podman` is required by Flexion)

- Update `docker-compose.yml` files to be platform independent
- Separate `docker-compose.yml` profiles into separate files
- Use `--production` dependencies in FE `Dockerfile` (same as production)

## How to test

Compose still works and automated tests pass.

## Definition of Done Checklist
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] Form validations updated

2024-11-06 19:17 UTC, fpigeonjr commented on frontend/Dockerfile
> +RUN bun install --production --frozen-lockfile
🤔 do we need the prod flag in localdev?

2024-11-06 19:19 UTC, fpigeonjr commented
how did you get around the pre-commit hook as seen here:

https://github.com/HHS/OPRE-OPS/pull/3029/files#r1830201896

2024-11-06 19:28 UTC, fpigeonjr commented on frontend/Dockerfile
> +RUN bun install --production --frozen-lockfile
maybe co-pilot agrees with me 🙃
<img width="469" alt="image" src="https://github.com/user-attachments/assets/0324025a-45b6-4dc1-a697-099218b580ce">

2024-11-06 19:33 UTC, fpigeonjr commented on frontend/Dockerfile
> +RUN bun install --production --frozen-lockfile
this is what the dev tools look like with prod flag 👎 
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/b66f3e22-73e4-450b-a7d6-d63ca6493755">

2024-11-06 19:34 UTC, fpigeonjr requested changes
Was able to get the app running with podman but don't think we want the prod flag for localdev since it effects the tooling:

`podman compose -f docker-compose.static.yml up --build`

2024-11-06 20:16 UTC, fpigeonjr commented on frontend/Dockerfile
> +RUN bun install --production --frozen-lockfile
this is what they should look like 👍 
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/18f7bfe7-845f-4b7d-87e9-b9d0c6cb5ffc">

2024-11-06 21:01 UTC, fpigeonjr approved these changes

2024-11-07 00:47 UTC, fpigeonjr commented
> Was able to get the app running with podman but don't think we want the prod flag for localdev since it effects the tooling:
> 
> `podman compose -f docker-compose.static.yml up --build`

disregard was running wrong command 🙃

2024-11-07 20:36 UTC, maiyerlee approved these changes

2024-11-12 14:35 UTC, merged